GitTools/GitReleaseManager

README.md
The link to CREDITS in ReadeMe.MD had a case-sensitive issue with the URL, which was resulting in a 404.
=> Stop the 'CREDITS' hyperlink giving a 404 error

docs/configuration/create-configuration.md, docs/configuration/default-configuration.md, docs/why-grm.md, mkdocs.yml
Fixes #93.
I had a look around to see if the `doc:pagename` syntax was supposed to be a thing because it's the first time I use MkDocs but I couldn't find anything so I suppose they were more of a reminder of what page each link had to go to.
I also enabled [strict mode](http://www.mkdocs.org/user-guide/configuration/#strict) in the config. This throws an error when a bad link is found instead of a warning. Let me know if you'd rather have a warning.
=> (GH-93) fix internal links in docs

Source/GitReleaseManager.Cli/Program.cs
This fix justs add the TLS 1.2 protocol to the ServicePointManager as a workaround to GitHub's new TLS 1.2 requirement. The correct approach should be to upgrade to latest Octokit, but upgrading from 0.17 to 0.29 contained too many breaking changes.
This should make it possible to do a service release.
=> Added fix for GitHub's new TLS 1.2 requirement.

.appveyor.yml, recipe.cake, tools/packages.config
Pin Cake.Recipe to 1.0.0 and build with required Cake version 0.3.2.1.
Also invalidates AppVeyor cache if build script has changed (instead of bootstrapper).
Fixes #130
=> (GH-130) Build with Cake.Recipe 1.0.0 / Cake 0.32.1

recipe.cake
This PR pretty much duplicates all of the tasks in Cake.Recipe that makes use of GitReleaseManager (with the exception of creating labels).
I noticed the issue, and figured, why not.
fixes #41
=> (GH-41) Implementing ability to dogfood GitReleaseManager during build

Source/GitReleaseManager.Cli/Options/BaseSubOptions.cs, Source/GitReleaseManager.Cli/Program.cs
This commit will add GRM as a figlet logo
unless the user specifies the argument
'--no-logo' on the commandline.
There will also not be any generation of
the logo when the user requests the help
or version section of the program.
example with the current pr branch:
resolves #38
=> (GH-38) Add generation of logo during runtime

Source/GitReleaseManager.Cli/GitReleaseManager.Cli.csproj, Source/GitReleaseManager.Cli/GitReleaseManager.Tool.csproj, Source/GitReleaseManager.Tests/ClipBoardHelper.cs, Source/GitReleaseManager.Tests/GitReleaseManager.Tests.csproj, Source/GitReleaseManager/GitReleaseManager.Core.csproj, nuspec/nuget/GitReleaseManager.nuspec, recipe.cake
This PR do the necessary work to remove almost all of the outputted warnings the occurs during building of GitReleaseManager.
There is one remaining warning (not counting those from Cake.Recipe) left that I have no idea of how to fix:
Issue from InspectCode:
```
Code Inspection Error(s) Located. Description:
File Name: ..\Packaging\nuget\GitReleaseManager.nuspec Line Number:  Message: No root tag defined
File Name: ..\Packaging\nuget\GitReleaseManager.Portable.nuspec Line Number:  Message: No root tag defined
```
THis issue also resolves issue #142 because it came up as a warning.
=> (maint) Fix warnings during building of GitReleaseManager

Source/GitReleaseManager.Tests/ConfigurationTests.cs, Source/GitReleaseManager.Tests/Resources.resx, Source/GitReleaseManager/Attributes/SampleAttribute.cs, Source/GitReleaseManager/Configuration/CommentSerialization/CommentGatheringTypeInspector.cs, Source/GitReleaseManager/Configuration/CommentSerialization/CommentsObjectDescriptor.cs, Source/GitReleaseManager/Configuration/CommentSerialization/CommentsObjectGraphVisitor.cs, Source/GitReleaseManager/Configuration/Config.cs, Source/GitReleaseManager/Configuration/ConfigSerializer.cs, Source/GitReleaseManager/Configuration/CreateConfig.cs, Source/GitReleaseManager/Configuration/ExportConfig.cs
This PR will change create a sample yaml file with the following output.
<details>
<summary>Sample Output</summary>
```yaml
#create:
#
#export:
#issue-labels-include:
#- Bug
#- Duplicate
#- Enhancement
#- Feature
#- Help Wanted
#- Improvement
#- Invalid
#- Question
#- WontFix
#issue-labels-exclude:
#- Internal Refactoring
#issue-labels-alias:
#- name: Documentation
#
```
</details>
Unfortunately it also changes a little bit of the output from `showConfig` (basically adding the comments only). If this is not desirable, let me know and I will look into changing it.
<details>
<summary>Default `showConfig` output</summary>
```yaml
create:
include-footer: false
footer-heading: ''
footer-content: ''
footer-includes-milestone: false
milestone-replace-text: ''
include-sha-section: false …
```
=> (GH-151) Add ability to create sample GitReleaseManager.yaml using yaml parser

.github/ISSUE_TEMPLATES/bug_report.md, .github/ISSUE_TEMPLATES/config.yml, .github/ISSUE_TEMPLATES/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This pull requests adds a couple of missing issue templates, a pull request template, a link to the Gitter channel on the issue list and disables creation of blank issues.
fixes #144 
To have a common template that can be used when creating issues/pull requests.
They haven't, but are similar to my own templates used in my projects.
=> (GH-144) Add templates for issues and pull requests

Source/GitReleaseManager.Cli/Program.cs, Source/GitReleaseManager.Tests/GitReleaseManager.Tests.csproj, Source/GitReleaseManager.Tests/ReleaseNotesBuilderIntegrationTests.cs, Source/GitReleaseManager/GitHubProvider.cs, Source/GitReleaseManager/OctokitExtensions.cs, Source/GitReleaseManager/ReleaseNotesBuilder.cs, Source/GitReleaseManager/ReleaseNotesExporter.cs
The GitReleaseManager is doing a lot of context switching when executing async methods.
Also calling `.Result` on Tasks is generally bad practice.
#161 
Fixes bad practices when using Tasks. This PR tries to solve:
- Stack traces being 💩 when there is an unhandled exception due to calling .Result on Tasks
- Methods are context switching a lot, leading to potential issues, if thread a Task tries to switch back to is blocked, leading to dead-locks
- Going async from entry point and all the way through the tool
Ran the test suite and ran the CLI tool to verify it still works.
=> (GH-161) Better async

Source/GitReleaseManager.Tests/Extensions/StringExtensionsTests.cs, Source/GitReleaseManager/Configuration/CloseConfig.cs, Source/GitReleaseManager/Configuration/Config.cs, Source/GitReleaseManager/Configuration/ConfigurationProvider.cs, Source/GitReleaseManager/Extensions/StringExtensions.cs, Source/GitReleaseManager/GitHubProvider.cs, Source/GitReleaseManager/ReleaseNotesBuilder.cs
This PR adds the ability to add a comment on closed issues (for a milestone/tag name) during the release publishing process.
fixes #128 
The motivation is to allow users of GRM to update users posting fixed issues that the changes is now part of the new release.
Tested by running GRM Locally, see the last comments on the following issues in a test repository: https://github.com/AdmiringWorm/FakeTestRepository/issues
I was a little unsure if the place to add this code should be during publishing, or during the closing of the milestone.
For now, I have added it during publishing but can change it to closing if that is more appropriate.
=> (GH-128) Add the ability to comment on issues during publish

Source/Directory.Build.props, Source/GitReleaseManager.IntegrationTests/GitReleaseManager.IntegrationTests.csproj, Source/GitReleaseManager.Tests/GitReleaseManager.Tests.csproj, Source/GitReleaseManager/GitReleaseManager.Core.csproj
This PR changes the unit tests libraries to target .NET Core 2.2 instead of 3.0 to fix the message about not being able to generate coverage reports for the .NET Core framework.
fixes #171 
Coverage reports should always be generated.
Locally, and through appveyor (custom instance)
=> (GH-171) Change target framework for unit tests to .NET Core 2.2

Source/GitReleaseManager.Tests/FakeGitHubClient.cs, Source/GitReleaseManager/GitHubProvider.cs, Source/GitReleaseManager/IVcsProvider.cs, Source/GitReleaseManager/ReleaseNotesBuilder.cs
Fix calls to `.Result` and use await or pass along a task
Fixes #175 
Ran unit tests
=> (GH-175) Remove the last couple of .Result calls

Source/GitReleaseManager.Cli/Options/OpenSubOptions.cs, Source/GitReleaseManager.Cli/Program.cs, Source/GitReleaseManager.Tests/FakeGitHubClient.cs, Source/GitReleaseManager/GitHubProvider.cs, Source/GitReleaseManager/IVcsProvider.cs
To allow the re-opening of a milestone, that might have been closed as
part of an aborted release.  This will help with the exercising of the
integration tests for GitReleaseManager.
Fixes #177 
Adding this command allows for reverting an action that can be done by GRM.  In the same way that we can discard a created release, we can now re-open a closed milestone.
Tested on Friday Lunch Time Stream, using the FakeRepository on the GitTools Organisation.
=> (GH-177) Add open command

Source/GitReleaseManager/GitHubProvider.cs
Currently GRM will write a warning to a log file when an asset isn't
there, but in this scenario, we feel it would be better to raise an
exception.
Fixes #108 
If the file doesn't exist, the user should be informed.  Otherwise, information from the release could get forgotten about.
No, not tested, but expected to work without it.
=> (GH-108) Raise exception when asset doesn't exist

Source/GitReleaseManager.Tests/ReleaseNotesBuilderTests.cs, Source/GitReleaseManager/ReleaseNotesBuilder.cs
If there are no closed issues assigned to a milestone, or if the issues
assigned to the milestone all have excluded labels, than a release
shouldn't get created.  Instead, an exception should be thrown.
Fixes #72 
Doesn't make sense to create a release when there are no valid issues assigned to the milestone.
Tested during stream using FakeRepository.
=> (GH-72) Don't create release when not required

Source/GitReleaseManager.Cli/Program.cs
Due to a mistake in a previous pull request the
open command was not made available to be used
as the OpenSubOptions class is not specifically
given to the CommandLineParser library.
This pull request makes this command available again.
No related issue
To make the open command available to be used.
Basic local debugging.
=> (maint) Fixed open command not available

Source/Directory.Build.props, Source/GitReleaseManager.Cli/GitReleaseManager.Cli.csproj, Source/GitReleaseManager.Cli/Program.cs, Source/GitReleaseManager.IntegrationTests/GitReleaseManager.IntegrationTests.csproj, Source/GitReleaseManager.IntegrationTests/ReleaseNotesBuilderIntegrationTests.cs, Source/GitReleaseManager.Tests/GitReleaseManager.Tests.csproj, Source/GitReleaseManager.Tests/ReleaseNotesBuilderTests.cs, Source/GitReleaseManager.Tests/ReleaseNotesExporterTests.cs, Source/GitReleaseManager/Configuration/ConfigurationProvider.cs, Source/GitReleaseManager/Exceptions/InvalidStateException.cs, Source/GitReleaseManager/Exceptions/MissingReleaseException.cs, Source/GitReleaseManager/GitHubProvider.cs, Source/GitReleaseManager/OctokitExtensions.cs, Source/GitReleaseManager/ReleaseNotesBuilder.cs, nuspec/nuget/GitReleaseManager.nuspec
This changes are mainly to make sonarlint happy, and to improve a bit.
Among these changes are:
- For Unit tests, also check the inner exception if it is the type it should be.
- For exception logging, output the inner exceptions of the aggregate exception
- Split async methods that throws exceptions to prevent AggregateException to be created when an exception is thrown in the beginning of the method (not all methods can be converted to this)
- Enable the generation of xml documentation (warnings for missing documentation have been disabled)
- Change the throwing of a normal Exception to be more specific
- Make sure streams are only disposed once.
- Other changes just to make sonarlint happy.
None
Best practices, and to get rid of warnings
Locally
=> (maint) Cleanup sonarlint warnings and recommendations

Source/GitReleaseManager/Configuration/ConfigurationProvider.cs, docs/input/docs/configuration/default-configuration.md
To prevent any confusion about whether or not Yaml config file is being used
or not, add a warning when it isn't being used.
Fixes #170 
In some circumstances, GRM can be ran from different directories, and this makes
it clear whether or not the YAML file is being used or not.
Not required.
=> (GH-170) Add warning for not using yaml config

Source/GitReleaseManager.Cli/Options/BaseVcsSubOptions.cs, Source/GitReleaseManager.Cli/Program.cs, Source/GitReleaseManager/GitHubProvider.cs, docs/input/docs/commands/_auth-notes.md, docs/input/docs/commands/_deprecated-args.md, docs/input/docs/commands/add-assets.md, docs/input/docs/commands/close.md, docs/input/docs/commands/create.md, docs/input/docs/commands/discard.md, docs/input/docs/commands/export.md, docs/input/docs/commands/label.md, docs/input/docs/commands/open.md, docs/input/docs/commands/publish.md
This pull request deprecates the use of a username and password for authentication (to be removed in the future).
fixes #158 
The motivation is two-fold.
1. GitHub have deprecated the authentication with a Username and Password
2. Will make it easier to Migrate to Spectre.Cli when we eventually can remove this authentication method.
Not tested. Logically it should work.
=> (GH-158) Deprecate the use of authentication with username+password

.gitignore, recipe.cake, tests/integration/buildData.cake, tests/integration/expected/releasenotes-with-token.md, tests/integration/expected/releasenotes-with-username-password.md, tests/integration/tests.cake, tests/integration/utilities.cake, tests/integration/xunit.cake
Cake.Recipe has the ability to run an additional Cake script to exercise specific functionality, in order to verify that things are working as expected.  This PR adds this for the various GRM Cake aliases.
Fixes #140 
Add integration tests will allow us to know that we haven't inadvertently broken something when adding new functionality. 
Tests have been ran against FakeRepository
=> (GH-140) Add integration tests

Source/GitReleaseManager/Configuration/Config.cs, Source/GitReleaseManager/Configuration/LabelConfig.cs, Source/GitReleaseManager/GitHubProvider.cs, docs/input/docs/configuration/default-configuration.md
=> (GH-188) Configure default labels

Source/GitReleaseManager.Core/Extensions/MilestoneExtensions.cs, Source/GitReleaseManager.Core/Extensions/OctokitExtensions.cs, Source/GitReleaseManager.Core/MappingProfiles/GitHubProfile.cs
Consolidate all extension classes into the extensions folder.
For consistency.
Fixes #271
https://github.com/GitTools/GitReleaseManager/issues/271
To safe our sanity
It hasn't, pushing to CI build
=> (GH-271) Move classes into extensions folder

docs/input/docs/commands/create.md, src/GitReleaseManager.Core.Tests/Commands/CreateCommandTests.cs, src/GitReleaseManager.Core.Tests/VcsServiceTests.cs, src/GitReleaseManager.Core/Commands/CreateCommand.cs, src/GitReleaseManager.Core/GitReleaseManager.Core.csproj, src/GitReleaseManager.Core/IVcsService.cs, src/GitReleaseManager.Core/Options/CreateSubOptions.cs, src/GitReleaseManager.Core/ReleaseNotes/IReleaseNotesBuilder.cs, src/GitReleaseManager.Core/ReleaseNotes/ReleaseNotesBuilder.cs, src/GitReleaseManager.Core/ReleaseNotes/ReleaseNotesTemplate.cs, src/GitReleaseManager.Core/VcsService.cs, src/GitReleaseManager.IntegrationTests/ReleaseNotesBuilderIntegrationTests.cs, src/GitReleaseManager.Tests/ReleaseNotesBuilderTests.cs, src/GitReleaseManager.Tests/VcsServiceMock.cs
=> (GH-217) Template based release notes creation

README.md
Add .NET global tool installation instructions and add fenced code language specifiers to the shell code blocks
It was not described how to install GitReleaseManager as a .NET Global tool. This PR adds that description to the README.
=> Add .NET global tool installation instructions

src/GitReleaseManager.Cli/Program.cs
Due to the service collection only being set up when a VCS command is being used, an exception
is throw on non-vcs commands (like showconfig).
Related to closed issue #181 
To be able to run non-vcs commands.
Local debugging.
=> (maint) Fixed service collection not being created on non-vcs commands

src/GitReleaseManager.Core.Tests/Commands/ExportCommandTests.cs, src/GitReleaseManager.Core.Tests/Provider/GitHubProviderTests.cs, src/GitReleaseManager.Core.Tests/VcsServiceTests.cs, src/GitReleaseManager.Core/Commands/ExportCommand.cs, src/GitReleaseManager.Core/IVcsService.cs, src/GitReleaseManager.Core/Options/ExportSubOptions.cs, src/GitReleaseManager.Core/Provider/GitHubProvider.cs, src/GitReleaseManager.Core/Provider/IVcsProvider.cs, src/GitReleaseManager.Core/VcsService.cs, src/GitReleaseManager.IntegrationTests/GitHubProviderIntegrationTests.cs, src/GitReleaseManager.Tests/VcsServiceMock.cs
This will allow the exclusion of pre-releases from the generated
markdown file. By default, all releases will be included.
Fixes #99
=> (#99) Add SkipPrereleases option

docs/input/docs/commands/create.md, src/GitReleaseManager.Core.Tests/Commands/CreateCommandTests.cs, src/GitReleaseManager.Core/Commands/CreateCommand.cs, src/GitReleaseManager.Core/IVcsService.cs, src/GitReleaseManager.Core/Options/CreateSubOptions.cs, src/GitReleaseManager.Core/VcsService.cs, src/GitReleaseManager.Tests/VcsServiceMock.cs
This is similar to the overload for passing in an input file, the
difference being that string.Empty is passed in, rather than reading
the contents of the file, and then creating a release.
#112
This allows the creation of an empty release, to allow for starting the release process, without having actually done any work.
New unit tests have been added, similar to existing functionality.
=> (#112) Add new method for creating empty release

src/GitReleaseManager.Core.Tests/Commands/InitCommandTests.cs, src/GitReleaseManager.Core/Configuration/ConfigurationProvider.cs
The changes in this pull requests adds an additional check to ensure that no new configuration file is created, even in the case that a configuration file with the old legacy name exist.
fixes #379
A new unit test has been created to test the new check.
=> (#379) Validate old config file do not exist

nuspec/nuget/GitReleaseManager.nuspec
GitReleaseManager.exe.config contains a AssemblyBinding-redirect
which is needed to use GitReleaseManager.exe.
fixes #399
#399 
* build and pack the nuget package
* unzip the nupkg
* cd into the tools folder
* call `GitReleaseManager.exe label --token a -o b -r c`
* #399 does no longer occur
=> (#399) included GitReleaseManager.exe.config in nuget

src/GitReleaseManager.Core.Tests/VcsServiceTests.cs, src/GitReleaseManager.Core/VcsService.cs
Address issue #454 
I can reproduce the issue when I execute the command below
```
grm create --milestone 2.0.1 --token [HIDDEN] --owner OWNER --repository [REPOSITORY] --assets "D:/Projects/project/Publish/xxx.2.0.1-beta.64.bin.zip", "D:/Projects/project/Publish/xxx.2.0.1-beta.64.setup.exe"
```
The problem is that when I'm getting the release, I'm trying to find a released tagged `2.0.1`. Because there's no release (sic.) with tag `2.0.1`, `NULL` is returned
https://github.com/GitTools/GitReleaseManager/blob/c0d8b8e4dd54e72c22126971b7fc2b44855c8e99/src/GitReleaseManager.Core/VcsService.cs#L136
Later, I'm trying to query the assets on a `NULL` collection of releases => `NullReferenceException`
https://github.com/GitTools/GitReleaseManager/blob/c0d8b8e4dd54e72c22126971b7fc2b44855c8e99/src/G …
=> Issue 454: Assets on a draft release can be null

src/GitReleaseManager.Cli/Program.cs, src/GitReleaseManager.Core.Tests/Provider/GitHubProviderTests.cs, src/GitReleaseManager.Core.Tests/VcsServiceTests.cs, src/GitReleaseManager.Core/Commands/AddAssetsCommand.cs, src/GitReleaseManager.Core/Commands/ExportCommand.cs, src/GitReleaseManager.Core/Commands/LabelCommand.cs, src/GitReleaseManager.Core/Configuration/Config.cs, src/GitReleaseManager.Core/Extensions/MilestoneExtensions.cs, src/GitReleaseManager.Core/GitReleaseManager.Core.csproj, src/GitReleaseManager.Core/MappingProfiles/GitHubProfile.cs, src/GitReleaseManager.Core/MappingProfiles/GitLabProfile.cs, src/GitReleaseManager.Core/Model/Issue.cs, src/GitReleaseManager.Core/Model/Milestone.cs, src/GitReleaseManager.Core/Model/VcsProvider.cs, src/GitReleaseManager.Core/Options/BaseVcsSubOptions.cs, src/GitReleaseManager.Core/Provider/GitHubProvider.cs, src/GitReleaseManager.Core/Provider/GitLabProvider.cs, src/GitReleaseManager.Core/Provider/IVcsProvider.cs, src/GitReleaseManager.Core/ReleaseNotes/ReleaseNotesBuilder.cs, src/GitReleaseManager.Core/Templates/default/issue-note.sbn, src/GitReleaseManager.Core/Templates/default/release-info.sbn, src/GitReleaseManager.Core/VcsService.cs, src/GitReleaseManager.IntegrationTests/GitHubProviderIntegrationTests.cs, src/GitReleaseManager.IntegrationTests/GitLabProviderIntegrationTests.cs, src/GitReleaseManager.Tests/ReleaseNotesBuilderTests.cs, src/GitReleaseManager.Tool/GitReleaseManager.Tool.csproj
This PR adds support to allow creation, and maintenance of, releases on GitLab.  This has been made possible using the NGItLab library.  There are some items that have been left unimplemented, see the commit messages for more details.
Fixes #146 
I work on some projects that use GitLab for private work, and I want the ability to create release notes in the same way as done on public projects on GitHub.
1. Create both a public and private repository on GitLab
2. Get token to allow maintenance of these projects
3. Create a milestone and some issues using standard GRM labels
4. Run the `create` command to create release from the milestone - this will create an "upcoming release"
5. Run the `discard` command to delete the release
6. Run the `create` command again
7. Run the `publish` command …
=> Add support for GitLab

src/GitReleaseManager.Cli/Logging/LogConfiguration.cs, src/GitReleaseManager.Core/Options/BaseSubOptions.cs
This updates the handling of how we output log messages to the console
to instead of blindly outputting warning messages to stderr all the
time, it will instead check if an environment variable called `CI` is
available and set to true, or the user themself have specified the
`--ci` argument.
When CI system is detected, any warnings will instead be outputted to
the normal stdout along with normal informational messages.
#fixes #439
Certain CI systems out there will abort the build every time something is written to stderr. This causes problems on these systems when GitReleaseManager is ran.
1. On a repository, create a milestone with a valid version and one that does not contain any versions.
2. Run `grm create 2>files.txt` with the appropriate arguments for the valid version, and ensure …
=> (#439) Add option to disable warning to stderr

src/GitReleaseManager.Core.Tests/Commands/CreateCommandTests.cs, src/GitReleaseManager.Core/Commands/CreateCommand.cs, src/GitReleaseManager.Core/Options/CreateSubOptions.cs
This updates how arguments are parsed when attempting to create a new
release. This disallows explicitly the use of a milestone, and an input
file path in the same call.
fixes #476
This is done as there was confusion on why specifying a input file path
was not using the release notes specified. This should make it clearer
to the caller what the issue is.
1. Run `grm create --milestone 0.5.0 -i some-relase-notes.txt` with additional valid arguments.
2. Ensure an exception is thrown explaining that these two arguments can not be used together.
=> (#476) Add validation of input file path handler

src/GitReleaseManager.Core/ReleaseNotes/ReleaseNotesBuilder.cs, src/GitReleaseManager.Tests/ReleaseNotesBuilderTests.CorrectlyExcludeIssuesWhenBothIncludeAndExcludeLabelIsSet.approved.txt, src/GitReleaseManager.Tests/ReleaseNotesBuilderTests.cs
This updates the handling on how we are excluding labels when generating
release notes.
This allows issues to be assigned with a normal label, but still be
excluded if a different label is listed in the exclusion list.
fixes #574
Previously you would need to add and remove labels between drafting a
release notes.
This has been tested by running through scenarios locally using my [FakeTestRepository](https://github.com/AdmiringWorm/FakeTestRepository)
=> (#574) Exclude all issues with label

src/GitReleaseManager.Cli/GitReleaseManager.Cli.csproj, src/GitReleaseManager.Core.Tests/GitReleaseManager.Core.Tests.csproj, src/GitReleaseManager.Core/GitReleaseManager.Core.csproj, src/GitReleaseManager.Core/Model/Issue.cs, src/GitReleaseManager.Tests/GitReleaseManager.Tests.csproj, src/GitReleaseManager.Tool/GitReleaseManager.Tool.csproj
Bumped Octokit to 10.0.0 to solve https://github.com/GitTools/GitReleaseManager/issues/578
https://github.com/GitTools/GitReleaseManager/issues/578
https://github.com/GitTools/GitReleaseManager/issues/578 prevents issue data from being fetched from GitHub due to issue/PR Id values that were previously `int` now being `long`.
Not sure testing this is really possible or appropriate. GitReleaseManager doesn't need the issue Id but the deserialization of the Issue data fails without the fix.
I did grab the CI-created NuGet package to test within our own environment to make sure it fixes the bug for us. _That is not yet complete._
=> (#578) Bump Octokit to 10.0.0 to fix oversized ints

recipe.cake, src/GitReleaseManager.Cli/GitReleaseManager.Cli.csproj, src/GitReleaseManager.Core.Tests/GitReleaseManager.Core.Tests.csproj, src/GitReleaseManager.Core/GitReleaseManager.Core.csproj, src/GitReleaseManager.Core/Model/IssueComment.cs, src/GitReleaseManager.Tests/GitReleaseManager.Tests.csproj, src/GitReleaseManager.Tool/GitReleaseManager.Tool.csproj
=> Upgrade Octokit reference and change IssueComment.Id to long

.github/dependabot.yml
Include `github actions` in the dependabot configuration
=> add github actions configuration for dependabot

.github/dependabot.yml
It is possible to group together several packages in one single PR. By default the PRs will have the `Build` label, which might be changed to something else after the PR is created
=> Groups for dependabot

src/Directory.Build.props, src/Directory.Packages.props, src/GitReleaseManager.Cli/GitReleaseManager.Cli.csproj, src/GitReleaseManager.Core.Tests/GitReleaseManager.Core.Tests.csproj, src/GitReleaseManager.Core/GitReleaseManager.Core.csproj, src/GitReleaseManager.Core/VcsService.cs, src/GitReleaseManager.IntegrationTests/GitReleaseManager.IntegrationTests.csproj, src/GitReleaseManager.Tests/GitReleaseManager.Tests.csproj, src/GitReleaseManager.Tool/GitReleaseManager.Tool.csproj, src/GitReleaseManager.sln
Convert the nuget package management to the central package management
=> convert nuget packages to use central package management

src/GitReleaseManager.Core/Configuration/CloseConfig.cs, src/GitReleaseManager.Core/Configuration/Config.cs, src/GitReleaseManager.Core/Model/Milestone.cs, src/GitReleaseManager.Core/Provider/GitHubProvider.cs, src/GitReleaseManager.Core/Provider/GitLabProvider.cs, src/GitReleaseManager.Core/VcsService.cs
Allow developers to set a Boolean setting indicating whether they want the due date to be set when a milestone is closed.
By default, this config setting is set to "false" to preserve the current behavior.
=> (#568) Set the 'Due date' when closing a milestone if configured to do so

docs/input/docs/configuration/default-configuration.md
This new config option will be available in GRM 0.19.0 (when PR #541  is merged).
=> Document the new include-contributors option
